### ISSUE TITLE
Unable to specify loadBalancerIp

### ISSUE THREAD

**Issue by chaoyangnz** [pulumi/pulumi-kubernetes-ingress-nginx#12]
### What happened?

```
const ingressExternalIp = new gcp.compute.Address('ingress-external-ip', {
    addressType: 'EXTERNAL',
    purpose: 'SHARED_LOADBALANCER_VIP',
});

const ingressNginxController = new ingressNginx.IngressController('ingress-nginx-controller', {
  controller: {
      publishService: {
          enabled: true,
      },
      service: {
          loadBalancerIPs: ingressExternalIp.address,
      },
  }
})
```

Then I got this error:

```
 warning: resource plugin kubernetes-ingress-nginx is expected to have version >=0.0.5, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin
    warning: resource plugin kubernetes-ingress-nginx is expected to have version >=0.0.5, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin
    error: Error: failed to register new resource ingress-nginx-controller [kubernetes-ingress-nginx:index:IngressController]: 2 UNKNOWN: setting args: copying input "controller": expected destination type to implement pulumi.Input or pulumi.Output, got string
        at Object.registerResource (/Users/chao.yang/Private/stackbase/node_modules/@pulumi/runtime/resource.ts:293:27)
        at new Resource (/Users/chao.yang/Private/stackbase/node_modules/@pulumi/resource.ts:393:13)
        at new ComponentResource (/Users/chao.yang/Private/stackbase/node_modules/@pulumi/resource.ts:881:9)
        at new IngressController (/Users/chao.yang/Private/stackbase/node_modules/@pulumi/ingressController.ts:62:9)
```

### Steps to reproduce

the above code

### Expected Behavior

Should be able to specify the IP address

### Actual Behavior

Error when run preview

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @chaoyangnz 

Have you built this provider yourself? It seems there's an ambient version of the provider on your path already

if you run the command:

`pulumi plugin ls` then what do you see? Do you see multiple versions of the provider installed?

Paul

**Comment by rshade** [comment]
Can you test 0.0.6?

**Comment by robertvanhoesel** [comment]
Confirming this issue is still present on 0.0.6 with only one version of kubernetes-ingress-nginx installed. 
It occurs to me it is the same issue as https://github.com/pulumi/pulumi-kubernetes-cert-manager/issues/1

**Comment by robertvanhoesel** [comment]
Additionally, setting a static string as displayed as a workaround in  does not work.

I believe the cause of this issue may actually be a typo (I though all properties where generated?) since the [actual Helm chart](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx#values) expects the singular `controller.service.loadBalancerIP` without an 's' instead of plural `controller.service.loadBalancerIPs`.

**Comment by robertvanhoesel** [comment]
For others experiencing issues with this package: I noticed more schema errors which may leave you scratching your head. I recommend using Helm.v3.Release directly like below

```ts
import * as k8s from "@pulumi/kubernetes";

const ns = new k8s.core.v1.Namespace("ingress-nginx", {}, { provider: kubernetes });
const namespace = ns.metadata.name;

const externalIp = new gcp.compute.Address('external-ip', { addressType: 'EXTERNAL' });

const ingressNginxController = new k8s.helm.v3.Release(
    "nginx-ingress",
    {
        chart: "ingress-nginx",
        version: "4.2.0",
        repositoryOpts: {
            repo: "https://kubernetes.github.io/ingress-nginx",
        },
        values: {
            controller: {
                publishService: {
                    enabled: true,
                },
                service: {
                    loadBalancerIP: externalIp.address,
                },
            },
        },
        namespace,
    },
    { provider: kubernetes }
);
```
