### ISSUE TITLE
Issue #16 was not fixed

### ISSUE THREAD

**Issue by MihaiSandor** [pulumi/pulumi-kubernetes-ingress-nginx#19]
### What happened?

Issue #16 was not fixed. 
The builds are failing and I cannot pull with go mod tidy
the new version of the package. See here: https://github.com/pulumi/pulumi-kubernetes-ingress-nginx/runs/7341405439?check_suite_focus=true

### Steps to reproduce

Just to go mod tidy

### Expected Behavior

To get a new version with latest fixes.

### Actual Behavior

I got the old version.

### Versions used

Latest

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by stack72** [comment]
Hi @MihaiSandor 

There's an issue I am investigating that go is complaining of docker moby not available - when that's taken care of, this will be working again

Paul

**Comment by MihaiSandor** [comment]
@stack72 Any updates?

**Comment by MihaiSandor** [comment]
up

**Comment by stack72** [comment]
Hi @MihaiSandor 

We are looking at this and aim to get a release out asap - the dependency is only seeming to be on these build runners so something isn't quite right

Paul

**Comment by MihaiSandor** [comment]
Hey @stack72, 

Almost half a month has passed and we still don't have
any release to be able to use this module. Do you have 
any idea when the release will be out?

Mihai
