### ISSUE TITLE
Support `pulumi-kubernetes` >= 4.0.0

### ISSUE THREAD

**Issue by benglewis** [pulumi/pulumi-kubernetes-ingress-nginx#40]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This repo only supports `pulumi-kubernetes` < 4.0.0, which is now very old, `pulumi-kubernetes` is on `4.11.0` already. I cannot use this package without support for the latest `pulumi-kubernetes`, since I do not want to downgrade my `pulumi-kubernetes` package.

### Affected area/feature

`pulumi-kubernetes` integration

**Comment by alextbok** [comment]
Is this repository still supported? cc @mikhailshilkov
